image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

before_script:
  - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"

build:
  stage: build
  script:
    - docker-compose -f ./django-pg-docker-tutorial-master/docker-compose.yml build
    - docker image tag django-pg-docker-tutorial-master-app:latest $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - docker push $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_TAG
