yandex_token     = "y0_AgAAAAAFHpDZAATuwQAAAAEMhsi8AACl_eo18yFKeZtxPO_LQAaNdas-iw"
cloud_id         = "org-b1giqm47plsf2o"
folder_id        = "b1gfpj90uvcng3d5s6mb"
public_key_path  = "/home/dimonius/.ssh/yc.pub"
private_key_path = "/home/dimonius/.ssh/yc"
