apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app
data:
  DB_HOST: db
  DB_NAME: tutorial-dev
  DB_USER: vinhle
  DB_PASS: password

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3003
          command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"]
          envFrom:
            - configMapRef:
                name: django-config

---

apiVersion: v1
kind: Service
metadata:
  name: django-app
  namespace: django-app
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
      nodePort: 30080  # Укажите порт в диапазоне 30000-32767

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgresql
          image: "postgres:13-alpine"
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.username}}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.password}}"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: tutorial-volume
      volumes:
        - name: tutorial-volume
          persistentVolumeClaim:
            claimName: postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: django-app
spec:
  selector:
    app: postgres-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
