apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: django-app 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  namespace: django-app 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.image.persistence.size | quote }}