---
# tasks file for k8s_create_cluster
- name: Initialize the Kubernetes cluster using kubeadm # инициализируем кластер
  become: yes
  become_user: root
  command: kubeadm init

- name: get permission # даем доступ для обычного пользователя
  shell: "{{ item }}"
  become_user: ubuntu
  with_items:
   - mkdir -p $HOME/.kube
   - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
   - sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install calico pod network # устанавливаем calico pod network
  become: false
  shell: "{{ item }}"
  with_items:
   #- kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.0/manifests/tigera-operator.yaml
   - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/calico.yaml
   
- name: Generate join command # показываем команду с добавлением ноды и записываем ее в переменную
  become: true
  command: kubeadm token create --print-join-command
  register: join_command
  
- name: Show join_command result
  debug:
    msg: "{{ join_command.stdout }}"

- name: Copy join command to local file # создаем локальный файл и добавляем туда переменную для присоединения ноды
  become: true
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
